In [1]:
import numpy as np
import time

In [2]:
size=1_00
list1 =list(range(size))
list2 =list(range(size))

start=time.time()
result=[x+y for x,y in zip(list1,list2)]
end=time.time()
print("Total time taken using list ",end-start)

Total time taken using list  0.0001049041748046875


In [3]:

arr1 =np.array(list1)
arr2 =np.array(list2)

start=time.time()
result=arr1 + arr2
end=time.time()
print("Total time taken using np array ",end-start)

Total time taken using np array  0.00011229515075683594


2. Creating numpy arrays

In [4]:
#Creating 1D
arr1=np.array([1,2,3,4,5])
print(arr1)
#Creating 2D
arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)
print("Type:" ,type(arr2))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>


3. Memory comparision

In [5]:
import sys
list_data=list(range(100))
numpy_data= np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")


Python list size: 85600 bytes
NumPy array size: 800 bytes


4. Vectorization

In [6]:
list_ele=[x**2 for x in list1]

numpy_ele=arr1*2