In [1]:
import numpy as np

In [6]:
arr=np.array([1,3,40])
print(arr)
print(type(arr))

[ 1  3 40]
<class 'numpy.ndarray'>


In [5]:
arr=np.array([[1,3,40],[1,3,40]])
print(arr)
print(type(arr))

[[ 1  3 40]
 [ 1  3 40]]
<class 'numpy.ndarray'>


In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(1,10,3)

array([1, 4, 7])

In [ ]:
np.linspace(0,2,10) #Equally spaced elements in a range

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [19]:
arr= np.array([[1,2,3],[2,3,4],[3,4,5]])
print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)



Shape: (3, 3)
Size: 9
Dimensions: 2
Data type: int64


In [22]:
arr= np.array([[1,2,3],[2,3,4],[3,4,5]],dtype=np.float32)
print(arr)
arr_int=arr.astype(np.int32)
print(arr_int)

[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)
 
reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]
 
flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]



(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
