In [1]:
import numpy as np

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
flat=arr.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
flat[0]

1

In [10]:
flat[4]

5

In [11]:
flat[3:6]

array([4, 5, 6])

In [ ]:
flat[:5] #Same as flat[0:5]

array([1, 2, 3, 4, 5])

In [13]:
flat[3:]

array([4, 5, 6, 7, 8, 9])

In [14]:
flat[::4]

array([1, 5, 9])

2.Slicing

In [15]:
b= flat[3:6]
b

array([4, 5, 6])

In [18]:
b[0]=3333
b

array([3333,    5,    6])

In [17]:
flat

array([   1,    2,    3, 3333,    5,    6,    7,    8,    9])

In [20]:
c=flat[5:].copy()
c[2]=33
print(c)
print(flat)

[ 6  7 33  9]
[   1    2    3 3333    5    6    7    8    9]


3. fancy indexing


In [21]:
arr=np.array([1,45,5,6,4,75,545,46,57])
idx=[0,2,3]
print(arr[idx])


[1 5 6]


4.Boolean Masking


In [22]:
arr[arr<10]

array([1, 5, 6, 4])