In [1]:
import numpy as np

In [2]:
arr= np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
np.mean(arr) #Mean

3.5

In [ ]:
np.std(arr) # Standard deviation

1.707825127659933

In [ ]:
np.var(arr) #Variance

2.9166666666666665

In [ ]:
np.min(arr) #Compute the minimum value of an array.

1

In [ ]:
np.max(arr) #Compute the maximum value of an array.

6

In [ ]:
np.sum(arr) #Compute the sum of all elements in an array.

21

In [ ]:
np.prod(arr) #Compute the product of all elements in an array.

720

In [ ]:
np.median(arr) # Compute the median of an array.

3.5

In [11]:
np.percentile(arr, 50)  # For the 50th percentile (median)

3.5

In [ ]:
np.argmin(arr) #Return the index of the minimum value in an array.

0

In [ ]:
np.argmax(arr) #Return the index of the maximum value in an array.

5

In [ ]:
arr2= np.array([[2,2,3],[3,3,3]])
np.corrcoef(arr, arr2) #Compute the correlation coefficient matrix of two arrays.

/home/anshuman/D_Drive/Coding/DataScience/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/anshuman/D_Drive/Coding/DataScience/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


array([[1.       , 1.       , 0.8660254,       nan],
       [1.       , 1.       , 0.8660254,       nan],
       [0.8660254, 0.8660254, 1.       ,       nan],
       [      nan,       nan,       nan,       nan]])

In [ ]:
np.unique(arr) #Find the unique elements of an array.

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.diff(arr) #Compute the n-th differences of an array.

array([[1, 1],
       [1, 1]])

In [ ]:
np.cumsum(arr) #Compute the cumulative sum of an array.

array([ 1,  3,  6, 10, 15, 21])

In [19]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.log(arr) #Compute the natural logarithm of an array.

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [ ]:
np.exp(arr) #Compute the exponential of an array.

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])